### ISSUE TITLE
mail/postfix: Postfix 3.6 compatibility checklist

### ISSUE THREAD

**Issue by windgmbh** [opnsense/plugins#2409]
## Required steps
in order to be Postfix 3.6 compatible:

- [x] OpenSSL 1.1.1 compatibility
- [ ] LibreSSL compatibility (→https://github.com/opnsense/ports/issues/128)
- [x] Do not use White-/Blacklists in postscreen (→ `allowlist`/ `denylist`).
*`postscreen` is currently not implemented in OPNsense.*
- [x] Do not use `md5` for TLS fingerprint digests (→ `sha256`) .
*TLS fingerprint digests are currently not implemented in OPNsense.*
- [x] Do not use export grade Diffie-Hellman key exchange
*TLS settings do not allow that.*
- [x] Do not use services database
- [ ] *optionally:* Install Postfix 3.5.11 (https://github.com/opnsense/ports/pull/130), which offers 3.6 configuration compatibility
- [ ]  Set `compatibility_level = 3.6` in `main.cf` (https://github.com/opnsense/plugins/pull/2454)

## Steps already taken

* Compiled and installed `postfix-sasl` on OPNsense 21.1.6 (OpenSSL). No compatibility warnings observed.
* Tried to compile `postfix-sasl` on OPNsense 21.1.6 (LibreSSL). Build failed due to https://github.com/opnsense/ports/issues/128

## Resources / References

* [Postfix 3.6.0 release notes](http://www.postfix.org/announcements/postfix-3.6.0.html)
* [Postfix compatibility readme](http://www.postfix.org/COMPATIBILITY_README.html)
* https://github.com/opnsense/plugins/issues/2255#issuecomment-851376363

**Comment by windgmbh** [comment]
@fichtner A while ago you have requested me to

> Next up: @windgmbh would you mind helping to test postfix 3.6 compatibility? FreeBSD ports already move to this version and it is said to have a few changes.
(https://github.com/opnsense/plugins/pull/2255#issuecomment-850215735)

Anything that I have found out can be found or is referenced by this issue. 

Basically we are probably stuck using Postifx 3.5.x until LibreSSL becomes fully OpenSSL 1.1.1 compatible.

**Comment by realizelol** [comment]
Are there any news here?

Checking for packages with security vulnerabilities:
Database fetched: Fri Sep 15 03:33:08 CEST 2023
postfix35-3.5.12_1,1: Tag: expiration_date Value: 2021-09-30
postfix35-3.5.12_1,1: Tag: deprecated Value: It is only here until FreeBSD 11 is EoL (Postfix >= 3.6 requires OpenSSL >= 1.1.x)

on latest updates:
OPNsense 23.7.4-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1v 1 Aug 2023

$ postconf mail_version
`mail_version = 3.5.12`
