### ISSUE TITLE
net/wireguard CARP vhid tracking not working if CARP temporarily disabled

### ISSUE THREAD

**Issue by nsty** [opnsense/plugins#3741]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I'd like to say thank you for the implementation of vhid tracking for wireguard #3579. I was waiting for this for a long time.
When temporarily disabling CARP, the vhid tracking of wireguard drops out though. The wireguard interfaces continue to run and interfere with the other CARP nodes, in particular the new master.

**To Reproduce**
1. Go to '/ui/diagnostics/interface/vip' on the current CARP master
2. Click on 'Temporarily Disable CARP'
3. CARP status changes to 'DISABLED'
4. Wireguard interfaces are still UP and RUNNING

**Expected behavior**
The wireguard interfaces should also be disabled as if the firewall would fall into CARP backup mode. It is working correctly when 'Enable Persistent CARP Maintenance Mode' is selected.
My guess is that it has something to do with the missing virtual IPs in the 'ifconfig' output.

**Relevant log files**
'ifconfig' snippets for three scenarios: CARP master, CARP temporarily disabled, CARP persistently disabled.

1. CARP fully functional and node is master.
```
lagg0_vlan2: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: WAN (opt1)
	options=4000000<NOMAP>
	ether 90:e2:ba:xx
	inet xx.xx.xx.248 netmask 0xffffffe0 broadcast xx.xx.xx.255
	inet xx.xx.xx.247 netmask 0xffffffe0 broadcast xx.xx.xx.255 vhid 1
	inet xx.xx.xx.229 netmask 0xffffffe0 broadcast xx.xx.xx.255 vhid 2
	inet xx.xx.xx.236 netmask 0xffffffe0 broadcast xx.xx.xx.255 vhid 3
	groups: vlan
	carp: MASTER vhid 1 advbase 1 advskew 0
	carp: MASTER vhid 2 advbase 1 advskew 0
	carp: MASTER vhid 3 advbase 1 advskew 0
	vlan: 2 vlanproto: 802.1q vlanpcp: 0 parent interface: lagg0
	media: Ethernet autoselect
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
wg0: flags=80c1<UP,RUNNING,NOARP,MULTICAST> metric 0 mtu 1420
	options=80000<LINKSTATE>
	inet 192.168.202.1 netmask 0xfffffffc
	groups: wg wireguard
	nd6 options=109<PERFORMNUD,IFDISABLED,NO_DAD>
```

2. CARP temporarily disabled, not working as expected.
```
lagg0_vlan2: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: WAN (opt1)
	options=4000000<NOMAP>
	ether 90:e2:ba:xx
	inet xx.xx.xx.248 netmask 0xffffffe0 broadcast xx.xx.xx.255
	groups: vlan
	vlan: 2 vlanproto: 802.1q vlanpcp: 0 parent interface: lagg0
	media: Ethernet autoselect
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
wg0: flags=80c1<UP,RUNNING,NOARP,MULTICAST> metric 0 mtu 1420
	options=80000<LINKSTATE>
	inet 192.168.202.1 netmask 0xfffffffc
	groups: wg wireguard
	nd6 options=109<PERFORMNUD,IFDISABLED,NO_DAD>
```

3. CARP permanently disabled, working as expected.
```
lagg0_vlan2: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: WAN (opt1)
	options=4000000<NOMAP>
	ether 90:e2:ba:xx
	inet xx.xx.xx.248 netmask 0xffffffe0 broadcast xx.xx.xx.255
	inet xx.xx.xx.247 netmask 0xffffffe0 broadcast xx.xx.xx.255 vhid 1
	inet xx.xx.xx.229 netmask 0xffffffe0 broadcast xx.xx.xx.255 vhid 2
	inet xx.xx.xx.236 netmask 0xffffffe0 broadcast xx.xx.xx.255 vhid 3
	groups: vlan
	carp: BACKUP vhid 1 advbase 1 advskew 0
	carp: BACKUP vhid 2 advbase 1 advskew 0
	carp: BACKUP vhid 3 advbase 1 advskew 0
	vlan: 2 vlanproto: 802.1q vlanpcp: 0 parent interface: lagg0
	media: Ethernet autoselect
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
wg0: flags=8080<NOARP,MULTICAST> metric 0 mtu 1420
	options=80000<LINKSTATE>
	inet 192.168.202.1 netmask 0xfffffffc
	groups: wg wireguard
	nd6 options=109<PERFORMNUD,IFDISABLED,NO_DAD>
```

**Environment**
OPNsense 23.7.10_1-amd64.

**Comment by AdSchellevis** [comment]
The disable button is a bit of a flawed concept, when removing all addresses (with their vhid's), there's nothing to track either. If it wasn't in there for so long already I would rather ditch the whole feature to be honest as there are likely more side-effects of using the hammer here.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/commit/9ff64a3e41428a2b23ae55846a5b92d498d47245 should do the trick
